.headers on

WITH CHANGES AS(
  SELECT
    DATE,
    SCHEMA AS NEW_SCHEMA,
    LAG(SCHEMA) OVER(ORDER BY DATE) AS PAST_SCHEMA
  FROM
    EXOPLANETS_SCHEMA
),

SCHEMA_CHANGE_INSTANCES AS(
  SELECT
    *
  FROM
    CHANGES
  WHERE
    NEW_SCHEMA != PAST_SCHEMA
  ORDER BY
    DATE ASC
)

-- TODO not working: is this possible using string splitting on ")," then calculating the diff? Will attempt
SELECT
  DATE,
  REPLACE(NEW_SCHEMA,PAST_SCHEMA,'') AS ADDED_FIELDS,
  REPLACE(PAST_SCHEMA,NEW_SCHEMA,'') AS DELETED_FIELDS
FROM
  SCHEMA_CHANGE_INSTANCES;
