CREATE TABLE EXOPLANETS_EXTENDED(
  _ID VARCHAR(16777216) NOT NULL,
  DISTANCE FLOAT,
  G FLOAT,
  ORBITAL_PERIOD FLOAT,
  AVG_TEMP FLOAT,
  DATE_ADDED TIMESTAMP_NTZ(6) NOT NULL,
  ECCENTRICITY FLOAT,
  ATMOSPHERE VARCHAR(16777216)
);